server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
      minMoney: 1
      description: 最少要发${minMoney}元
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luckymoney?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: seen328266
  jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
